## DEEP LEARNING
### PYTORCH basic

In [1]:
import torch
torch.cuda.is_available()
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1650'

In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

torch.cuda.is_available()
torch.device("cuda")

device(type='cuda')

In [4]:
df = pd.read_csv("./Lab 1/Iris.csv")
df
df.shape

(150, 6)

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

#chia tập dữ liệu với test size 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

In [6]:
# tính đạo hàm bằng pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5 + 1
#tính y'
import torch

# Khởi tạo x (ví dụ x = 2.0)
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm y
y = 2 * x**4 + x**3 + 3 * x**2 + 5*x + 1

# Tính đạo hàm dy/dx
y.backward()

print("y =", y.item())
print("y' =", x.grad.item())

y = 63.0
y' = 93.0


In [7]:
torch.__version__

'2.9.1+cu126'

In [10]:
# chuyển đổi mảng numoy sang tensor pytorch

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)   # int64

# Chuyển NumPy array sang PyTorch LongTensor
tensor = torch.from_numpy(arr)    # tự nhận dtype từ NumPy
print(tensor)
print(tensor.dtype)  # torch.int64



[1 2 3 4 5]
int64
tensor([1, 2, 3, 4, 5])
torch.int64


In [14]:
arr2 = np.arange(12).reshape(4, 3)
print("NumPy array:")
print(arr2)
print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)

NumPy array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)
Dtype: int64


In [25]:
x=torch.from_numpy(arr)
print(x)

tensor([99,  1,  2,  3,  4])


In [21]:
arr[0]= 99
print(x)

tensor([99,  1,  2,  3,  4])


In [22]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [23]:
arr[0]= 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN4 :giải thích 2 tr hợp  ở trên , tại sao
# BTVN5 
# bạn giúp thầy tạo tensor với
# empty
# zeros
# ones
# random
# reshape với view và view as