## DEEP LEARNING
### PYTORCH basic

In [4]:
import torch 
torch.cuda.is_available() 
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1650'

In [8]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

torch.cuda.is_available()
torch.device("cuda")

device(type='cuda')

In [9]:
df = pd.read_csv("./Iris.csv")
df
df.shape

(150, 6)

In [11]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

#chia tập dữ liệu với test size 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

In [12]:
# tính đạo hàm bằng pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5 + 1
#tính y'
import torch

# Khởi tạo x (ví dụ x = 2.0)
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm y
y = 2 * x**4 + x**3 + 3 * x**2 + 5*x + 1

# Tính đạo hàm dy/dx
y.backward()

print("y =", y.item())
print("y' =", x.grad.item())

y = 63.0
y' = 93.0


In [13]:
torch.__version__

'2.5.1+cu121'

In [14]:
# chuyển đổi mảng numoy sang tensor pytorch

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)   # int64

# Chuyển NumPy array sang PyTorch LongTensor
tensor = torch.from_numpy(arr)    # tự nhận dtype từ NumPy
print(tensor)
print(tensor.dtype)  # torch.int64



[1 2 3 4 5]
int64
tensor([1, 2, 3, 4, 5])
torch.int64


In [15]:
arr2 = np.arange(12).reshape(4, 3)
print("NumPy array:")
print(arr2)
print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)

NumPy array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)
Dtype: int64


In [16]:
x=torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [17]:
arr[0]= 99
print(x)

tensor([99,  2,  3,  4,  5])


In [18]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [19]:
arr[0]= 99
print(x)

tensor([0, 1, 2, 3, 4])


BT1: cho y = 5x^5 + 6x^3 – 3x + 1 Cho biết độ dốc của đa thức trên ở điểm nào 

BT2: tạo 1 tensor ban đầu có giá trị là 2 Định nghĩa hàm số và tính gradient Y = x^3 + 2x^2 + 5x + 1 Hãy tính dy/dx tại giá trị của x Dùng phương pháp gradient descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 50 vòng lặp 

BT3: tạo 1 tập dữ liệu giả lập với x là số giờ học( ngẫu nhiên từ 1 – 10) và y là số điểm đ… theo công thức y =3x + 5 + noise Với noise là 1 giá trị ngẫu nhiên nhỏ 1 khởi tạo tham số ư và b ngẫu nhiên với requires_grad = True 2 tính MSE 3 tính gradient 4 cập nhật tham số w và b bằng gradient descent với learning rate alpha = 0.1 5 lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của nó 

BT4 :giải thích 2 trường hợp ở trên , tại sao 

BT5 : bạn giúp thầy tạo tensor với 
empty 
zeros 
ones 
random 
reshape với view và view as

In [ ]:
'''BT1: cho y = 5x^5 + 6x^3 - 3x + 1 Cho biết độ dốc của đa thức trên ở điểm nào '''
import torch

x = torch.tensor(2.0, requires_grad=True)
y = 5*x**5 + 6*x**3 - 3*x + 1
y.backward()

print(x.grad)


tensor(469.)


In [33]:
'''
BT2: tạo 1 tensor ban đầu có giá trị là 2 Định nghĩa hàm số và 
tính gradient Y = x^3 + 2x^2 + 5x + 1 Hãy tính dy/dx tại giá trị của x 
Dùng phương pháp gradient descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 50 vòng lặp 
'''
# Y = x^3 + 2x^2 + 5x + 1
# 1 tensor ban đầu có giá trị là 2 (x = 2)
# learingrate alpha = 0.1   
import torch

x = torch.tensor(2.0, requires_grad=True)
alpha = 0.1

for _ in range(50):
    if x.grad is not None:
        x.grad.zero_()
        
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    
    with torch.no_grad():
        x -= alpha * x.grad

print("x =", x.item())
print("dy/dx =", x.grad.item())



x = nan
dy/dx = nan


In [35]:
'''
BT3: tạo 1 tập dữ liệu giả lập với x là số giờ học( ngẫu nhiên từ 1 - 10) và y là số điểm đ… theo công thức y =3x + 5 + noise 
Với noise là 1 giá trị ngẫu nhiên nhỏ 
1 khởi tạo tham số ư và b ngẫu nhiên với requires_grad = True 
2 tính MSE 3 tính gradient 
4 cập nhật tham số w và b bằng gradient descent với learning rate alpha = 0.1
5 lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của nó '''
import torch

# tạo dữ liệu giả lập
x = torch.randint(1, 11, (100, 1)).float()      # số giờ học
noise = torch.randn(100, 1) * 0.5               # noise nhỏ
y = 3*x + 5 + noise                             # số điểm

# khởi tạo tham số w, b
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

alpha = 0.1

# gradient descent 100 vòng lặp
for _ in range(100):
    # dự đoán
    y_pred = w*x + b
    
    # tính MSE
    loss = ((y_pred - y)**2).mean()
    
    # tính gradient
    loss.backward()
    
    # cập nhật w, b
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    # reset gradient
    w.grad.zero_()
    b.grad.zero_()

print("w =", w.item())
print("b =", b.item())



w = nan
b = nan


BT4 :giải thích 2 trường hợp ở trên , tại sao 

TH1

x=torch.from_numpy(arr) 

print(x) 

-> tensor([99, 1, 2, 3, 4]) 

--------------------------------------------------------- 

arr[0]= 99 

print(x) 

-> tensor([99, 1, 2, 3, 4]) 

TH2 

arr = np.arange(0,5) 

x = torch.tensor(arr) 

print(x) 

-> tensor([0, 1, 2, 3, 4]) 

--------------------------------------------------------- 
arr[0]= 99 

print(x) 

-> tensor([0, 1, 2, 3, 4])

Sở dĩ ở trường hợp trên tensor có giá trị 99 còn ở trường hợp dưới thì không, là do cách PyTorch tạo tensor khác nhau. 

Khi dùng `torch.from_numpy(arr)`, tensor và mảng NumPy dùng chung vùng nhớ, nên khi giá trị của `arr` thay đổi thì tensor cũng thay đổi theo. 

Ngược lại, khi dùng `torch.tensor(arr)`, PyTorch tạo ra một tensor mới bằng cách sao chép dữ liệu, nên sau khi tạo tensor, việc thay đổi mảng NumPy không ảnh hưởng đến tensor, vì hai bên không còn liên kết bộ nhớ với nhau.


In [45]:
'''
BT5 : bạn giúp thầy tạo tensor với 
-empty 
-zeros 
-ones 
-random 
-reshape với view và view as
'''
import torch

a = torch.empty(2, 3)
b = torch.zeros(2, 3)
c = torch.ones(2, 3)
d = torch.rand(2, 3)

x = torch.arange(12)
y = x.view(3, 4)
z = x.view_as(y)

print(a)
print(b)
print(c)
print(d)
print(y)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7110, 0.8512, 0.6588],
        [0.2301, 0.8640, 0.9724]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
