# Deep learning 2

## Tuần 2: Numpy, pandas, matplotlib

#NUMPY

In [1]:
# Numpy là thư viện kiểu list
# Vì:
# nhanh
# có nhiều hàm tích hợp cho AI
# để sd numpy thì : pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list 
python_list = [1,2,3,4,5]# tạo list
print("python list:", python_list)# in ra list

# chuyển đổi dsach trên thành numpy list
numpy_list = np.array(python_list) # chuyển đổi
print("numpy list:", numpy_list) # in ra numpy list
type(numpy_list)    # kiểm tra kiểu dữ liệu

python list: [1, 2, 3, 4, 5]
numpy list: [1 2 3 4 5]


numpy.ndarray

In [3]:
#list trong python có thể hỗ trợ nhiều kiểu dữ liệu khác nhau
my_list = [1, "chào", 3.6, True]    # tạo list hỗn hợp voiws nhiều kiểu dlieu # nhau
print("in ra danh sách tùm lum kiểu dlieu:", my_list)

in ra danh sách tùm lum kiểu dlieu: [1, 'chào', 3.6, True]


In [4]:
my_list = [1, 2, 3, 4, 5.6]   # tạo list có số thực và nguyên
np_list = np.array(my_list) # chuyển đổi thành numpy list
np_list # in ra numpy list

array([1. , 2. , 3. , 4. , 5.6])

In [5]:
# chuyển đổi kiểu dữ liệu trong numpy thì sao?
np_list_int = np_list.astype(int) # chuyển đổi thành kiểu int 
np_list_int # in ra numpy list đã chuyển đổi

array([1, 2, 3, 4, 5])

In [6]:
# accessing và indexing trong numpy
x = np.array([[1,2,3],[4,5,6]]) # tạo mảng 2d
x =np.array(range(1,9))
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
x[2:]


array([3, 4, 5, 6, 7, 8])

In [8]:
# lấy từ 3 - 8 theo 3 cách
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [9]:
x[2:]


array([3, 4, 5, 6, 7, 8])

In [10]:
#lấy 3-5
x[2] ,x[4]

(np.int64(3), np.int64(5))

In [11]:
# đặt dsach các index muốn truy cập
x[[2,4]]

array([3, 5])

In [12]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
#Lấy só 2
np_list[0,1]


np.int64(2)

In [14]:
#Lấy só 3
np_list[2,1]

np.int64(6)

In [15]:
#lấy [3,4],[5,6]
#cach 1
np_list[1]
np_list[1:]

array([[3, 4],
       [5, 6]])

In [16]:
#cách 2
np_list[1:3]


array([[3, 4],
       [5, 6]])

In [17]:
#cach 3
np_list[1:,0:2]

array([[3, 4],
       [5, 6]])

In [18]:
#cách 7: sử dụng boolean indexing
np_list[np.array([False, True, True])]

array([[3, 4],
       [5, 6]])

In [19]:
#cách 4: sử dụng số âm (lấy 2 hàng cuối)
np_list[-2:]    # lấy hàng thứ 2 từ cuối trở đi 

array([[3, 4],
       [5, 6]])

In [20]:
#Lấy 1 , 3 , 5
# lấy 1,3,5 (cột 0 của mỗi hàng)
#cách 1
np_list[:,0]
#cách 2
print(np_list[0:3, 0])

print(np_list[[0,1,2], 0])

print(np_list[:, 0:1])

[1 3 5]
[1 3 5]
[[1]
 [3]
 [5]]


In [21]:
# lấy 1 và 5 theo 2 cách

# Cách 1 chỉ đình hàng 0 cột 2 và cột 0
print(np_list[[0,2], 0])

# Cách 2:(::2 lấy mỗi hàng thứ 2) ( step bước nhảy)
print(np_list[::2, 0])

[1 5]
[1 5]


In [22]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
# lấy 2,6,10,14 
print(np_list[:, 1])   # lấy tất cả các hàng cột 1
print(np_list[0:4, 1])# lấy từ hàng 0 đến hàng 3 cột 1
print([[0,1,2,3], 1])# lấy 2,6,10,14

[ 2  6 10 14]
[ 2  6 10 14]
[[0, 1, 2, 3], 1]


In [24]:
#lây 7 và 11 
print(np_list[1],2)

[5 6 7 8] 2


In [25]:
# lấy 4 7 10
np_list[[0,1,2], [3,2,1]] 

array([ 4,  7, 10])

In [26]:
# lấy 16 15 14 13
print(np_list[3, ::-1]) #Lấy hàng 3, đảo ngược cột (step -1)    
print(np_list[-1, ::-1]) #Lấy hàng cuối (-1), đảo ngược cột
print(np_list[3, [3,2,1,0]]) # lấy ở hàng 4 chỉ định 3210= [13, 14, 15, 16]])

[16 15 14 13]
[16 15 14 13]
[16 15 14 13]


In [ ]:
'''
BTVN thú zị :>
B1: cho ma trận = [ [99,99,99],
                    [99,99,99],
                    [99,99,99]]
Hãy tưởng tượng ô 99 trống 
- giả sử 1 là x
- giả sử 0 là o
Lấy đầu vào từ phía x và phía o luân phiên
-Nếu đầu vào từ phía x là (0,0)
thì ma trận sẽ trở thành
                [   [x,99,99],
                    [99,99,99],
                    [99,99,99] ]
Nếu đầu vào từ phía o cũng là (0,0)
- thông báo họ nhập lại
- nếu không thì điền vào ma trận

* thử thách : Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi
'''
import numpy as np

board = np.full((3,3), 99)
player = 1   # 1 = X, 0 = O

def win(b, p):
    for i in range(3):
        if np.all(b[i]==p) or np.all(b[:,i]==p):
            return True
    return np.all(np.diag(b)==p) or np.all(np.diag(np.fliplr(b))==p)

while True:
    print(board)

    r = int(input())
    c = int(input())

    if board[r, c] != 99:
        print("Nhập lại")
        continue

    board[r, c] = player

    if win(board, player):
        print(board)
        print("Thắng")
        break

    player = 1 - player
    
    ''' 
    Ví trí ô:
(0,0) (0,1) (0,2)
(1,0) (1,1) (1,2)
(2,0) (2,1) (2,2)
- Mỗi lượt nhập 2 số
- Dòng 1: hàng (0–2)
- Dòng 2: cột (0–2)
    '''


[[99 99 99]
 [99 99 99]
 [99 99 99]]
[[ 1 99 99]
 [99 99 99]
 [99 99 99]]
[[ 1 99 99]
 [99 99 99]
 [99  0 99]]
[[ 1  1 99]
 [99 99 99]
 [99  0 99]]
[[ 1  1 99]
 [99 99 99]
 [ 0  0 99]]
[[ 1  1  1]
 [99 99 99]
 [ 0  0 99]]
Thắng


In [ ]:
'''
B2: cho y = [   [1,2,3],
                [4,5,6]
                [7,8,9]]
Lấy 4,5,6
Lấy 2,5
Lấy 3,4
Lấy 9,6,3
'''

y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(y[1])        # 4, 5, 6
print(y[:, 1])     # 2, 5, 8
print(y[[0,1], [2,0]]) # 3, 4
print(y[:, 2][::-1])      # 9, 6, 3


[4 5 6]
[2 5 8]
[3 4]
[9 6 3]


In [9]:
'''
B3: cho x = [1,2,3,4,5,6,7,8,9,10]
- xuất ra các giá trị chẵn theo sử dụng if
- xuất ra các giá trị chẵn theo sử dụng list comprehension
'''
np_x = np.arange(10)

print(np_x)
print(np_x % 2 == 0)

idx = [True,True,True,False,True,True,True,False,True,False]
print(np_x[idx])

cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0
print(np_x[cond1 & cond2 | cond3])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 1 2 4 5 6 8]
[1 2 3 4 5 6 7 8 9]


In [21]:
'''
B4: tạo 1 mảng numpy có kích thước 150x5
- giả sử mã này chưa 150 mẫu dữ liệu của sinh viên 
bao gồm : chiều cao - cân nặng - tuổi - lương - điểm trung bình
- tách mảng dự trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cung thành y 
- tách mảng x thành x_train và x_test 
trong đó: x_train chứa 70% dữ liệu
- tách y thành y_train  và y_test 
trong đó y_train chứa 0% dữ liệu
-tạo 10 tập dữ liệu x_train không chồng chéo nhau
'''
import numpy as np

data = np.random.rand(150, 5) # tạo mảng 150x5 

X = data[:, :4] # tách X thành 4 cột đầu tiên
y = data[:, 4] # tách y thành cột cuối cùng

n_train = int(0.7 * len(X)) # tính số mẫu cho tập huấn luyện (70%)
X_train = X[:n_train] # tách X_train chứa 70% dữ liệu
X_test  = X[n_train:] # tách X_test chứa 30% dữ liệu

y_train = y[:0]        # mảng rỗng
y_test  = y 

X_folds = np.array_split(X_train, 10) # tạo 10 tập dữ liệu không chồng chéo nhau

print(X_folds)



[array([[0.79140946, 0.02209976, 0.64096483, 0.43406827],
       [0.90080884, 0.86214784, 0.45648407, 0.5395401 ],
       [0.7069155 , 0.02910586, 0.19235019, 0.66278778],
       [0.18866361, 0.18694514, 0.05910779, 0.83141007],
       [0.08900131, 0.35839557, 0.79748015, 0.34490309],
       [0.73746538, 0.96290437, 0.65824941, 0.55457062],
       [0.19013983, 0.55807239, 0.24053764, 0.53724936],
       [0.10324195, 0.0470024 , 0.0023039 , 0.54479024],
       [0.54110131, 0.11607759, 0.90197942, 0.31516681],
       [0.64980808, 0.93367003, 0.16335508, 0.59819337],
       [0.92618386, 0.04007505, 0.56258693, 0.05793703]]), array([[0.63911291, 0.92123978, 0.77388335, 0.69466679],
       [0.326124  , 0.98123624, 0.94396908, 0.21414924],
       [0.14722537, 0.54469937, 0.37461865, 0.40586461],
       [0.79766111, 0.41167448, 0.27714987, 0.7542694 ],
       [0.87260316, 0.2530498 , 0.194864  , 0.6667732 ],
       [0.27492229, 0.95348085, 0.4684223 , 0.58716373],
       [0.61822021, 0.583852